### ISSUE TITLE
When using Ditto (in Male/Genderless) with Female, IVs are assigned to the incorrect gender

### ISSUE THREAD

**Issue by zetx** [rngchan/sun-moon-rng#10]
Hello, per subject line, when I'm using a Ditto and a Female Pokemon, the IVs appear to be swapped.

This is my [config and results](https://gist.github.com/zetx/08f1b0fbe972c42ada4908aecf238d10).

In game, on hatching the egg with a Ditto and Female Lycanroc, I am getting the second set of IVs (IV Spread: (M, 29) / (M, 29) / (R, 17) / (F, 6) / (M, 31) / (M, 31))

If I say the Male is not a Ditto *or* that the Female is a Ditto, results.txt return the actual values of the egg. (Full disclosure, I modified a print so the egg seeds would be 0x instead of [hex]L however I did revert to stock 0.10.3 files when writing this issue)

(edit: To verify this, I used the "japanese tool" [listed here](https://twitter.com/pokemon_PhD/status/812754211775467520). Screenshot below.)
![image](https://cloud.githubusercontent.com/assets/290071/21515232/4fa770c8-cc93-11e6-8e86-b4a38e9a9494.png)

**Comment by RoLau** [comment]
I've actually just ran into the same problem where putting a ditto in with a female grimer, The egg that's supposed to hatch is supposed to be M/M/M/M/F/R, however it's rolling as F/F/M/M/F/R. in this case my 31 IVs are rolling in the 20s from the F grimer I'm using. Well shit lol(tested with 9.5 as well as 10.3)

**Comment by zetx** [comment]
I'm not sure of the significance of having Ditto as the second parent (Line ~330), but considering the issue arises when Ditto is the first parent (and is then switched to second), maybe it isn't needed? I can't read the JP articles on the egg seed stuff though

**Comment by RoLau** [comment]
I'm curious if using your work around to get the correct values to display retains the correct seed after hatching. Also does that 'japanese tool' have the same error or does it function normally?

**Comment by zetx** [comment]
I don't think the workaround works. I've been having issues with this tool today with a Ditto and female parent (both with and without the workaround). Haven't tried it again with a male parent (will do so tomorrow). The japanese tool seems to be outputting correctly, but I've only looked at it as far as the initial comment. Honestly, I like the output of results.txt better and I don't mind the setup with config.txt and what not.

**Comment by RoLau** [comment]
I hear ya, my own breeding projects are on hold for now because I lost my seed doing a quick exchange the other day (might be related to this actually) and had to refind it, so now I don't want to breed anything until we've figured out how to remedy this issue. I guess until then I could breed a bunch of eevees though since that in particular doesn't use ditto lol.

**Comment by RoLau** [comment]
There is also an issue I've run into where in the same situation, the hatched pokemon's ability is incorrect as well.

**Comment by rngchan** [comment]
I'll look into it. Seems I misread something from the disassembler, or maybe forgot to implement some condition on when Ditto should be the second parent in the algorithm. Shouldn't be a hard fix...

**Comment by rngchan** [comment]
Should be fixed as of version 0.10.4. It's very possible that this change caused another bug somewhere else, but from my tests I couldn't catch any. Maybe this is the bugless version~

Problem was that the parent switch wasn't necessary after all, the order should always be male/female as parents A/B, regardless of Ditto. Slight oversight on interpreting the disassembly.

I'll leave this open so you guys can confirm it's working as of the latest version without any more bugs.

**Comment by RoLau** [comment]
Looks like the seed after hatching can also display without the leading 0, testing a string of breeding projects to see if the forecasted results come out with no problems.

**Comment by RoLau** [comment]
So far so good, 3 different mons came out as predicted, now to see if turning off MM will muck it all up.

**Comment by zetx** [comment]
Sorry for the delay, tested a Ditto/Female and Ditto/Male and all the eggs came out as expected. Looks good to me. :)

**Comment by rngchan** [comment]
Guess it's time to close this since no one has had more issues with this.
