### ISSUE TITLE
result.txt not showing up

### ISSUE THREAD

**Issue by ghost** [rngchan/sun-moon-rng#15]
I did everything right, Command Prompt shows Done! message but no results.txt file is in the folder.

EDIT: Nevermind, it's working now. It's still showing another issue, though. It says that I have an invalid nature for my parent, but I really don't:
SLOT: 1NATURE: JollyIS DITTO: N
SLOT: 1NATURE: ImpishIS DITTO: Y

**Comment by rngchan** [comment]
I'll assume you're using Windows. Notepad for some reason doesn't break lines properly, so it kinda looks like you have everything on the same line. Try opening it in Wordpad, Notepad++ or any other text editor and see if you can get a config that looks like the sample to work.

**Comment by ghost** [comment]
Aha... I was having a similar issue, but this fixed it. Thanks for responding!
On a side note, my intent was to use this for shiny hatching. It just told me I need to accept 441 eggs and reject 31 eggs to get to the next shiny... >.<

**Comment by rngchan** [comment]
I'll close this for now since no more issues came up.
