### ISSUE TITLE
Found no shiny

### ISSUE THREAD

**Issue by Bolpi** [rngchan/sun-moon-rng#2]
There's something very strange, let me explain the problem. Yesterday i tested your program, it worked VERY WELL. I think i was lucky because i had a shiny in 16 rejected eggs. So i got it and i immediatly put the next seed (after i hacked it) on the program. It display that the next shiny will be at 9000+ rejected eggs. So what i did is making 2 box of magikarp to decrease that counter, and it became only 22 rejected eggs. I tough it was really great, 2 shiny in a day. But the strage thing is: now the program doesn't display any other shiny. I made like 20+ eggs from the second shiny but even if i put different seed (that i simply change hatching some eggs) it display 0 results (i checked many times the config, i even toggled the shiny option, it works without the shiny in the child option). Do you think that the game is that scripted? I mean, there is like a "cooldown" from a shiny to another if you are "too lucky" to find 2 in one day? Because i can't explain that to myself because your program should say when my other shiny will come, even if it will be like after 20k eggs

**Comment by brutalgg** [comment]
I don't believe that is an accurate statement that the game would be "scripted" to prevent two shiny hatches in a day. Some TSV values may have more "collisions" with the the sudoRNG that results in more or less shiny hatching capability.

**Comment by Bolpi** [comment]
But it worked for 2 shiny hatches in a day! I can't explain why it should display NOTHING now. What do you think i should do? Hatching lot and random eggs to "increments" my seed?

**Comment by brutalgg** [comment]
So there are a number of variables which can be adjusted for adjusting odds.. changing parents will have an affect or cycling the seed a bit by hatching would potentially make a difference. If you haven't changed parents that may the first thing I try. Parent IVS and items would determine viable hatches. This is still very early on so things are still being worked through. Try and play with it.

**Comment by Bolpi** [comment]
I'll try it right now, brb when i have more info. I think that it will be interesting for more people

**Comment by earthchie** [comment]
I got no shinies too

Finally after 4 hours, I finished finding my seed

1011000111011000110100010011000101111110010000000010100010100110000100000011011100000011101000000011010011101111110100001011111

which I turned it into 
a8ac28ad cf54ffa9 45ca2e87 2c4a43bb

then run update_seed.py and got this

```
Current Seed is:
State 3: f5efc6ed
State 2: 5d1cd361
State 1: c97358cc
State 0: 62f0cca7
```

So I copied into config.txt

```
======================
MALE/GENDERLESS PARENT
======================
HP IV: 31
ATK IV: 31
DEF IV: 31
SPATK IV: 31
SPDEF IV: 31
SPD IV: 31
HELD ITEM: Destiny Knot
ABILITY SLOT: 1
NATURE: Calm
IS DITTO: Y

======================
     FEMALE PARENT    
======================
HP IV: 31
ATK IV: 31
DEF IV: 31
SPATK IV: 31
SPDEF IV: 31
SPD IV: 31
HELD ITEM: Everstone
ABILITY SLOT: 1
NATURE: Adamant
IS DITTO: N

======================
     CHILD TRAITS     
======================
HP IV INTERVAL: [0, 31]
ATK IV INTERVAL: [0, 31]
DEF IV INTERVAL: [0, 31]
SPATK IV INTERVAL: [0, 31]
SPDEF IV INTERVAL: [0, 31]
SPD IV INTERVAL: [0, 31]
ABILITY SLOT: Anything
NATURE: Anything
GENDER: Anything
BALL: Anything
HIDDEN POWER TYPE: Anything
SHINY: Y

======================
    RNG PARAMETERS    
======================
STATUS 3: 0xf5efc6ed
STATUS 2: 0x5d1cd361
STATUS 1: 0xc97358cc
STATUS 0: 0x62f0cca7
TSV: 3707
   
======================
     OTHER OPTIONS    
======================
GENDER RATIO: 1-1
MASUDA METHOD: Y
SHINY CHARM: Y
SAME SPECIES: Y
SHOW THIS MANY RESULTS: 10
```

But this is what I got
![image](https://cloud.githubusercontent.com/assets/7013039/21404243/d20c5a74-c7f2-11e6-85ef-1c2cdffe92e6.png)

oh dear... I think I have a really bad luck. 

I don't gave up, I tried to hatch not-shiny pokemon to ensure that my seed is correct.
The next hatch will be 31.31.31.0.31.31 and I hatched exactly mon like your script predicted.

What a relief, at least I know my seed is correct. but still no shiny though...

Well, what should I do?

**Comment by shadowofdarkness** [comment]
You just have very bad luck I tested with your seed and TSV info and found your next shiny frames start at 13,313 then another group at 17,675

I don't think this script can search that far ahead as I had to use the Japanese program to find that. Guess you're just going to collect 395 eggs then then reject one to get to a shiny.

**Comment by rngchan** [comment]
Sorry for taking a while to show up, day's been rough. To the people that had trouble finding some results, the script stops looking 10000 frames ahead of your current seed to avoid running for minutes hogging your CPU, possibly creating bad user experience. If you want, you can edit line 315 to any other value (defaults at 10000). The line reads as follows:

```python
while len(results) < params["nresults"] and tries < 10000:
```

The original plan was to let this be a user configuration, but to keep it simple I simply timed it out at a large number, mostly because of the already large amount of user configuration parameters. 

I can update the script to write a meaningful message to results.txt so that users are not left blind as to why they are not getting results. I'll reconsider adding it as another configuration for the config file.

**Comment by earthchie** [comment]
Thanks guys.

![image](https://cloud.githubusercontent.com/assets/7013039/21420998/2ce3c836-c863-11e6-810d-d7bd94f4e4ca.png)

Well no choice. I have 400 eggs to go then

--
Edit: For the record, after 412 eggs I finally got this. This project is awesome!

![image](https://cloud.githubusercontent.com/assets/7013039/21458112/7e70cb32-c966-11e6-999a-5a85b0525381.png)

**Comment by rngchan** [comment]
So I believe it's a case of bad luck with RNG, and that @Bolpi simply didn't have a shiny within 10000 frames for their seed. Reading everything again I think I should clear something up:

* Advancing an egg advances, on average, 32 frames.
* Rejecting an egg advances exactly 1 frame.

This is why you can just accept a bunch of eggs to advance your seed, but it shouldn't reroll it. I'm curious about @Bolpi 's experience with the 9000+ rejects to only 22 by breeding two boxes of Magikarps, which shouldn't really be possible. This either means they rerolled their seed somehow, or 9000 was a bit of exaggeration. If possible, can you include some details on how you got that number to drop? Did you do anything special between breeding eggs?

That said, just to reiterate, the script only looks 10000 frames ahead, and you can change it yourself by looking at the previous comments. Changing it to higher values means the script will run for a longer time, finding more and more results.

Edit: I need input from @Bolpi to analyze this issue further, or to conclude it as simply a case of the desired egg being more than 10000 frames away, closing the issue.

**Comment by Bolpi** [comment]
Yeah, the problem was the 10000+ frames, i didn't know that when i was using the script. And man, i'm not joking about the 9000+ eggs. I simply saw that the next shiny will be after 9000 refused eggs, i thought that i could simply hatch, for example, a lot of magikarp in order to decrease that amount. Maybe i confused the result from another one, but i'm not 100% sure about that. Now i have the next shiny egg at 9800 refused egg. If i'll notice something (maybe more that 32 frames skipping from each egg) i'll open another thread. Thanks for the help btw

**Comment by rngchan** [comment]
Closing this issue since the problem has been resolved then. If you confirm / see that weird behavior with the seed jumping around again, please open a new issue.
