### ISSUE TITLE
[Question] Can I just hatch 127 eggs in a row?

### ISSUE THREAD

**Issue by earthchie** [rngchan/sun-moon-rng#3]
It kinda pain to soft-reset and hatches every single egg.

**Comment by brutalgg** [comment]
No. The sequence of soft resetting and rejecting moves the seed forward by one making it possible to determine your seed location. This would not be possible hatching eggs in succession.

**Comment by brutalgg** [comment]
This is also not an actual issue. :)

**Comment by earthchie** [comment]
ok thanks for your quick reply.
sorry for asking question here.

**Comment by brutalgg** [comment]
No worries. Happy to answer just letting you know.
