### ISSUE TITLE
Don't know if it was answered in a previous issue, but my current seed came out weird.(New problem, rngchan save me)

### ISSUE THREAD

**Issue by RoLau** [rngchan/sun-moon-rng#7]
I inputted my 127 bit shit into here http://blog.livedoor.jp/x_x_saki_x_x/RNG/SMBreeding.html
and got a resulting hex of this: 594ea7c7 9105829e 92133701 169a9142. Now when I put this into my seed.txt and ran the update seed script, I got this 

Current Seed is:
State 3: 74d2b4f
State 2: 9533d960
State 1: 522342a8
State 0: f752a3fe

Something's missing from State 3 or am I just being a dummy?

**Comment by rngchan** [comment]
Hi there, the "missing" part from state 3 is a leading 0. The number is 0x074d2b4f, but just like you shorten 010 to 10, it got shortened to 0x74d2b4f. Plugging it in as is in the config file should still make everything work as expected.

**Comment by RoLau** [comment]
Ah, I was just being a dummy then.

**Comment by RoLau** [comment]
Quick inquiry, about how long does it take to generate a results.txt? I might have a slow computer...

**Comment by earthchie** [comment]
For me it took less than 2 seconds. my cpu is kinda old too (Intel Core i5 750)

**Comment by RoLau** [comment]
So an i5-4440 CPU @ 3.10 GHz shouldn't be taking half an hour+ then ey...

**Comment by earthchie** [comment]
may be you have disk problem?

**Comment by RoLau** [comment]
that would be unfortunate, any idea how i could examine for such a problem?

**Comment by earthchie** [comment]
dunno just a random guess. let's try open task manager then go to tap performance.

run the script and let's see if your Disk hit 100% (or perhaps CPU, Memory)
![image](https://cloud.githubusercontent.com/assets/7013039/21462390/62f7fd1c-c98e-11e6-8bf8-614268444be7.png)

**Comment by brutalgg** [comment]
Results should be generated within a few seconds. Something is definitely wrong if you are having to wait more then a couple of minutes. I would save your config and re-download source code to see if the resolves your issue. If not there may be an issue with your computer.

**Comment by RoLau** [comment]
![with rngabuse running](https://cloud.githubusercontent.com/assets/24733140/21462525/aff8b3e8-c922-11e6-8b88-188502556387.png)
This is running the rngabuse.py with the following config.txt
======================
MALE/GENDERLESS PARENT
======================
HP IV: 31
ATK IV: 31
DEF IV: 31
SPATK IV: 31
SPDEF IV: 31
SPD IV: 31
HELD ITEM: Destiny Knot
ABILITY SLOT: 1
NATURE: Adamant
IS DITTO: N

======================
     FEMALE PARENT    
======================
HP IV: 31
ATK IV: 31
DEF IV: 31
SPATK IV: 31
SPDEF IV: 31
SPD IV: 31
HELD ITEM: Everstone
ABILITY SLOT: HA
NATURE: Calm
IS DITTO: N

======================
     CHILD TRAITS     
======================
HP IV INTERVAL: [31, 31]
ATK IV INTERVAL: [0, 31]
DEF IV INTERVAL: [31, 31]
SPATK IV INTERVAL: [31, 31]
SPDEF IV INTERVAL: [31, 31]
SPD IV INTERVAL: [31, 31]
ABILITY SLOT: HA
NATURE: Calm
GENDER: F
BALL: Anything
HIDDEN POWER TYPE: Anything
SHINY: Y

======================
    RNG PARAMETERS    
======================
STATUS 3: 0x074d2b4f
STATUS 2: 0x9533d960
STATUS 1: 0x522342a8
STATUS 0: 0xf752a3fe
TSV: 1554
ESV: []

======================
     OTHER OPTIONS    
======================
GENDER RATIO: 7-1
MASUDA METHOD: Y
SHINY CHARM: Y
SAME SPECIES: Y
SHOW THIS MANY RESULTS: 40


I decided to see if I could spit out a result with an errata in the config, so I changed the male HP IV to 32 and it spat out a result immediately, granted it was to let me know there was an error.

I'm running python 3.6 on win 10. if that helps any

**Comment by brutalgg** [comment]
What happens if you change from SHINY: Y to SHINY: Anything under child traits.

**Comment by RoLau** [comment]
>_> it spat out a result immediately.

[results.txt](https://github.com/rngchan/sun-moon-rng/files/671464/results.txt)

**Comment by RoLau** [comment]
It spat out this results.txt
http://pastebin.com/GxxFe2e7

**Comment by RoLau** [comment]
They must really not want this shiny F HA eevee to happen.

**Comment by brutalgg** [comment]
My speculation is that you are, unfortunately, very unlucky. It looks as though the shiny value is so far ahead that the script is taking an extended amount of time to run.

**Comment by RoLau** [comment]
If you have a super powerful computer, give it a run and let's see if your machine spits out a result. This could be hilarious.

**Comment by RoLau** [comment]
I changed child results to 

======================
     CHILD TRAITS     
======================
HP IV INTERVAL: [0, 31]
ATK IV INTERVAL: [0, 31]
DEF IV INTERVAL: [0, 31]
SPATK IV INTERVAL: [0, 31]
SPDEF IV INTERVAL: [0, 31]
SPD IV INTERVAL: [0, 31]
ABILITY SLOT: HA
NATURE: Calm
GENDER: F
BALL: Anything
HIDDEN POWER TYPE: Anything
SHINY: Y

Still no result being spat out. send help

**Comment by brutalgg** [comment]
I'm not getting anything. Looks like luck isn't on your side.

**Comment by brutalgg** [comment]
I checked in the Japanese tool as well and didn't get any results

**Comment by earthchie** [comment]
please wrap your config with tripple `` ` `` like this:
```
    ```
    config
    ```
```

**Comment by earthchie** [comment]
Hey I found a result!

config.txt (please double check)

```
======================
MALE/GENDERLESS PARENT
======================
HP IV: 31
ATK IV: 31
DEF IV: 31
SPATK IV: 31
SPDEF IV: 31
SPD IV: 31
HELD ITEM: Destiny Knot
ABILITY SLOT: 1
NATURE: Adamant
IS DITTO: N

======================
     FEMALE PARENT    
======================
HP IV: 31
ATK IV: 31
DEF IV: 31
SPATK IV: 31
SPDEF IV: 31
SPD IV: 31
HELD ITEM: Everstone
ABILITY SLOT: HA
NATURE: Calm
IS DITTO: N

======================
     CHILD TRAITS     
======================
HP IV INTERVAL: [31, 31]
ATK IV INTERVAL: [0, 31]
DEF IV INTERVAL: [31, 31]
SPATK IV INTERVAL: [31, 31]
SPDEF IV INTERVAL: [31, 31]
SPD IV INTERVAL: [31, 31]
ABILITY SLOT: HA
NATURE: Calm
GENDER: F
BALL: Anything
HIDDEN POWER TYPE: Anything
SHINY: Y

======================
    RNG PARAMETERS    
======================
STATUS 3: 0x074d2b4f
STATUS 2: 0x9533d960
STATUS 1: 0x522342a8
STATUS 0: 0xf752a3fe
TSV: 1554

======================
     OTHER OPTIONS    
======================
GENDER RATIO: 7-1
MASUDA METHOD: Y
SHINY CHARM: Y
SAME SPECIES: Y
SHOW THIS MANY RESULTS: 40
```

Here the result

```
IV Spread: (F, 31) / (R, 28) / (F, 31) / (M, 31) / (M, 31) / (M, 31)
Ability: HA
Nature: CALM
Gender: F
Ball Inherited: M
Hidden Power Type: DRAGON
PID: 5516477
ESV: 1554
Shiny: Yes
Seed to hatch: f0964d36 2c7ef798 ca1a67a3 b66fc82d
Seed after hatching: 7afb1ef8 ab2cd542 bdcb47ba 472247fe
Sequence of actions to hatch:
(This one might not work, still working the details)
>Accept 85 eggs
>Reject 28 eggs
>Accept egg
(This one will work for sure, but is longer)
>Reject 2978 eggs
>Accept egg
```

**Comment by brutalgg** [comment]
Interesting you're using an older version of the Scripts prior to using the ESV's. I don't get results with ESV's blank.

**Comment by brutalgg** [comment]
I just verified with an older version your config above.
>IV Spread: (F, 31) / (R, 28) / (F, 31) / (M, 31) / (M, 31) / (M, 31)
>Ability: HA
>Nature: CALM
>Gender: F
>Ball Inherited: M
>Hidden Power Type: DRAGON
>PID: 5516477
>ESV: 1554
>Shiny: Yes
>Seed to hatch: f0964d36 2c7ef798 ca1a67a3 b66fc82d
>Seed after hatching: 7afb1ef8 ab2cd542 bdcb47ba 472247fe
>Sequence of actions to hatch:
>(This one might not work, still working the details)
>>Accept 85 eggs
>>Reject 28 eggs
>>Accept egg
>(This one will work for sure, but is longer)
>>Reject 2978 eggs
>>Accept egg

**Comment by RoLau** [comment]
I'm confused, an older version of the scripts? I downloaded the current version of the zip here, and @earthchie what did you mean by putting ``` around config?

Alternatively, how do I get ahold of an older version so it works lol

**Comment by brutalgg** [comment]
In short it seems like there is something going wrong with the newest version. Try using the [9.5](https://github.com/rngchan/sun-moon-rng/archive/0.9.5.zip) release.

**Comment by RoLau** [comment]
ok i got the same result with HP dragon on the eevee using the older version, going to go through the motions to hatch it and see if it'll end up shiny. will check back in with results

**Comment by rngchan** [comment]
Guys, you can attach files to your comments. No need to paste your config file here, just attach it.

Back to the point, seems there is an issue with the latest release, then. It must be ignoring something about shininess when ESV is blank? I'll investigate further. For reference, if you want to download an earlier release, you can go here:

https://github.com/rngchan/sun-moon-rng/releases

0.9.5 should work flawlessly. Going to patch this up so 0.10.3 should work flawlessly, too.

**Comment by rngchan** [comment]
Turns out it was something extremely stupid that went right over my head when testing the script.

Everything should be working as of version 0.10.3. Thanks to everyone that helped diagnose it and guide @RoLau through things in my absence. I'll close this since it's supposedly resolved in an older version, but if you still have trouble feel free to open it again.
